# Generated by Django 3.0.3 on 2022-11-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='СurrencyBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Currency', models.CharField(max_length=100, verbose_name='Выберните валюту')),  # хранение названия валют
                ('Curs_BANK', models.IntegerField()),  # хранение курса валюты от банка
                ('Kurs_sell', models.IntegerField()),  # хранение курса продажи валюты
                ('Kurs_buy', models.IntegerField()),  # хранение курса покупки валюты
                ('date', models.DateTimeField()),  # хранение даты, когда была добавлена валюта
            ],
        ),
    ]
