# Generated by Django 3.0.3 on 2022-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сurrencybase',  # Имя модели, для которой изменяются опции
            options={'verbose_name': 'база_валют', 'verbose_name_plural': 'база_валюты'},  # Настройка отображаемого имени модели в административной панели
        ),
        migrations.RemoveField(
            model_name='сurrencybase',  # Имя модели, из которой удаляется поле
            name='date',  # Имя удаляемого поля
        ),
        migrations.AddField(
            model_name='сurrencybase',  # Имя модели, в которую добавляется новое поле
            name='number_of_currency',  # Имя нового поля
            field=models.IntegerField(default=1),  # Тип поля и его значение по умолчанию
            preserve_default=False,  # Указывает, что поле добавляется без сохранения предыдущего значения по умолчанию
        ),
    ]
