# Generated by Django 3.0.3 on 2022-11-25 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20221125_2000'),
    ]

    operations = [
        migrations.RenameModel(  # переименования модели
            old_name='СurrencyBase',  # Старое имя 
            new_name='Food',  # Новое имя 
        ),
    ]
